### ISSUE TITLE
How to use Continuous Variables for IF-THEN constraints on DOCPLEX (Python)?

### ISSUE THREAD

**Issue by Alizak97** [ctzhu/docplex#1]
I'm using DOCPLEX to build up a Mixed Integer Linear Programming (MILP) problem which is then solved via CPLEX on Python. However, upon trying to solve the MILP problem using IF-THEN constraints, I receive the following error:

`DOcplexException: Model.if_then(), nbBus40 >= 3.0 is not discrete`

This is happening because I have declared nbbus40 variable to be continuous, as shown in the code below:

`from docplex.mp.model import Model`
`mdl = Model(name='buses')`
`nbbus40 = mdl.continuous_var(name='nbBus40')`
`nbbus30 = mdl.integer_var(name='nbBus30')`
`mdl.add_constraint(nbbus40*40 + nbbus30*30 >= 300, 'kids') `
`mdl.add(mdl.if_then((nbbus40>=3),(nbbus30>=7)))`
`mdl.minimize(nbbus40*500 + nbbus30*400)`
`mdl.solve()`
`for v in mdl.iter_integer_vars():`
`    print(v," = ",v.solution_value)`

However, if I keep the nbbus40 variable as an integer, then I get the solution to the MILP problem, as shown below:

`from docplex.mp.model import Model`
`mdl = Model(name='buses')`
`nbbus40 = mdl.integer_var(name='nbBus40')`
`nbbus30 = mdl.integer_var(name='nbBus30')`
`mdl.add_constraint(nbbus40*40 + nbbus30*30 >= 300, 'kids') `
`mdl.add(mdl.if_then((nbbus40>=3),(nbbus30>=7)))`
`mdl.minimize(nbbus40*500 + nbbus30*400)`
`mdl.solve()`
`for v in mdl.iter_integer_vars():`
`    print(v," = ",v.solution_value)`

RESULT:

`nbBus40  =  0`
`nbBus30  =  10.0`

How can I use the IF-THEN constraint in DOCPLEX for continuous variables?

**Comment by ctzhu** [comment]
No you can't.  Certainly for the bus problem the number of buses has to be integer.  However, should the number of the larger bus be relaxed to continuous, you can use indicator constrains to achieve something similar:

```mdl = Model(name='buses')
nbbus40 = mdl.continuous_var(name='nbBus40')
nbbus30 = mdl.integer_var(name='nbBus30')
mdl.add_constraint(nbbus40*40 + nbbus30*30 >= 300, 'kids')
b40ge3 = mdl.binary_var()
mdl.add_indicator(b40ge3, nbbus40 >= 3)
mdl.add_indicator(b40ge3, nbbus30 >= 7)
mdl.minimize(nbbus40*500 + nbbus30*400)
mdl.solve(log_output=True)
```

In this case 7.5 big buses and 0 small bus would be the solution.

**Comment by Alizak97** [comment]
@ctzhu, can you kindly explain how the value of the binary variable ```b40ge3``` is assigned a **true** or **false** in the following line:

```mdl.add_indicator(b40ge3, nbbus40 >= 3)```

**Comment by ctzhu** [comment]
http://ibmdecisionoptimization.github.io/docplex-doc/mp/_modules/docplex/mp/model.html#Model.add_indicator by default indicator constraint has an activate value of 1, meaning when the binary variable has a value of 1, the 2nd argument which is a linear constraint must be satisfied, other wise the linear constraint might or might not be satisfied. 
That being said it is in theory necessary to add another indicator here 
`mdl.add_indicator(b40ge3, nbbus40 <= 2, 0)` but often times it is not necessary. 

Certainly in this case an alternative is to write those constraints as bigM: https://en.wikipedia.org/wiki/Big_M_method, `nbbus40 -3 >= M*(b40g3 -1)` but since major solvers nowadays all support indicators (CBC2.10 being the exception) there is no reason not to use it.
